### PR TITLE
Add LLaMA-Factory inference walkthrough using RESTful interface

### PR DESCRIPTION
**Pull request by llewelld**
Authored by Navdeep Kaur.

Adds Navdeep's walkthrough for using LLaMA-Factory using curl via the RESTful interface or the OpenAI API.

### CODE REVIEW

**Comment by llewelld** [comment]
I successfully tested the steps provided by Navdeep and the inference worked nicely. However, as I reformatted the steps into markdown from Navdeep's original document, I may have introduced errors.

**Comment by tomaslaz** [comment]
I recommend restructuring the changes by creating a new directory under ‘examples’ and moving all the files related to this example (scripts, images, markdown files) there.

**Comment by llewelld** [comment]
Thanks @tomaslaz, that's a really good idea. I've restructured it with a new directory under `examples`.

**Comment by llewelld** [comment]
Rebased.

**Comment by llewelld** [comment]
Retargeted to main.

**Comment by llewelld** [comment]
Merging in to avoid an accumulation of dependent branches. We can make further edits afterwards.

**Pull request merged**
